FROM openjdk:17


ENV SERVER_PORT=8061

ENV SPRING_DATA_MONGODB_USER=""
ENV SPRING_DATA_MONGODB_PASSWORD=""
ENV SPRING_DATA_MONGODB_URI=mongodb://172.17.0.1:32769/CRYPTO_MSG
ENV SPRING_DATA_MONGODB_AUTOINDEXCREATION=true


COPY target/CryptoMsg-0.0.1-SNAPSHOT.jar /app.jar


CMD ["java", "-jar", "/app.jar"]