---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: msg-database-metadata
spec:
  serviceName: msg-database
  replicas: 1
  selector:
    matchLabels:
      app: msg-db-app
  template:
    metadata:
      labels:
        app: msg-db-app
    spec:
      containers:
        - name: crypto-msg-database
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: 'CR1_MSG'
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: 'localapp'
            - name: MONGO_INITDB_DATABASE
              value: 'CRYPTO_MSG_DB'
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi